[hud]
	# Enable HUD display.
	showHud = false
	# Enable custom HUD range.
	# NOTE enabling is more computationally expensive on the client side.
	hudRangeEnabled = false
	# The distance that the HUD can be seen from (in blocks).
	# Vanilla default = 3.
	# Default: 3
	# Range: 0 ~ 100
	hudRange = 3
