[hud]
	# Enable HUD display.
	showHud = false
	# Enable HUD display when mob is at Level 0
	showLevel0Hud = false
	# The HUD x-offset.
	# Default: 0
	# Range: -1000 ~ 1000
	hudXOffset = 0
	# The HUD y-offset.
	# Default: 0
	# Range: -1000 ~ 1000
	hudYOffset = 0
	# Use dark theme HUD.
	useDarkThemeHud = true
	# Moves the Stronger Mobs Below HUD beside (to the left) of the WAILA HUD.
	# This setting is ignored if hudXOffset or hudYOffset are set (not 0).
	enableWailaIntegration = false
	# Moves the Stronger Mobs Below HUD beside (to the left) of the Champions HUD.
	# This setting will supercede enableWailaIntegration.
	# This setting is ignored if hudXOffset or hudYOffset are set (not 0).
	enableChampionsIntegration = false
