[[nameConfigs]]
	id = "strongermobsbelow:default"
	# white/blacklists of mods/mobs to apply this naming config to.
	# use "*" to whitelist all mods.
	modWhiltelist = []
	# if using "*" to whilte all mods, you can blacklist specific mods, while allowing all others.
	modBlacklist = []
	# by default, only zombie variants and skeleton variants are whitelisted.
	mobWhitelist = []
	# you can narrow allowable mobs, but adding individual mobs to the blacklist
	# ex. "minecraft" is added to the modWhitelist, allowing all vanilla mobs, but you could add "minecraft:creeper" to the blacklist.
	mobBlacklist = []
	# difficulty-name pairs. if a difficulty is not defined, then the default "Level" name will be used.
	[[nameConfigs.difficultyNames]]
		difficulty = 0
		name = "Vanilla"
	# difficulty-name pairs. if a difficulty is not defined, then the default "Level" name will be used.
	[[nameConfigs.difficultyNames]]
		difficulty = 1
		name = "Brute"
	# difficulty-name pairs. if a difficulty is not defined, then the default "Level" name will be used.
	[[nameConfigs.difficultyNames]]
		difficulty = 2
		name = "Captain"
	# difficulty-name pairs. if a difficulty is not defined, then the default "Level" name will be used.
	[[nameConfigs.difficultyNames]]
		difficulty = 3
		name = "Elite"
	# difficulty-name pairs. if a difficulty is not defined, then the default "Level" name will be used.
	[[nameConfigs.difficultyNames]]
		difficulty = 4
		name = "Champion"
	# difficulty-name pairs. if a difficulty is not defined, then the default "Level" name will be used.
	[[nameConfigs.difficultyNames]]
		difficulty = 5
		name = "Dreadnought"
